//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlitFactory.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlitFactory.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act number.
        /// </summary>
        internal static string ActNumberLabel {
            get {
                return ResourceManager.GetString("ActNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressLabel {
            get {
                return ResourceManager.GetString("AddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency abbreviation.
        /// </summary>
        internal static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect picture.
        /// </summary>
        internal static string DefectPictureLabel {
            get {
                return ResourceManager.GetString("DefectPictureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defective act.
        /// </summary>
        internal static string DefektacijasAktsTitle {
            get {
                return ResourceManager.GetString("DefektacijasAktsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string DefektācijasAprakstsLabel {
            get {
                return ResourceManager.GetString("DefektācijasAprakstsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect number.
        /// </summary>
        internal static string DefektaNrLabel {
            get {
                return ResourceManager.GetString("DefektaNrLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        internal static string DefektiLabel {
            get {
                return ResourceManager.GetString("DefektiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defects.
        /// </summary>
        internal static string DefektiTitle {
            get {
                return ResourceManager.GetString("DefektiTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this entry?.
        /// </summary>
        internal static string DeleteConfirmationLabel {
            get {
                return ResourceManager.GetString("DeleteConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string DiagnostikaLabel {
            get {
                return ResourceManager.GetString("DiagnostikaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defective act and defect pictures are in attachment..
        /// </summary>
        internal static string EmailSubjectLabel {
            get {
                return ResourceManager.GetString("EmailSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;b&gt;Act number  {DefektacijasAkts.AktaNr}&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        internal static string epastaTeksts {
            get {
                return ResourceManager.GetString("epastaTeksts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration of the equipment (Kv).
        /// </summary>
        internal static string EquipmentCallibrationLabel {
            get {
                return ResourceManager.GetString("EquipmentCallibrationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment name.
        /// </summary>
        internal static string EquipmentLabel {
            get {
                return ResourceManager.GetString("EquipmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        internal static string EquipmentMenu {
            get {
                return ResourceManager.GetString("EquipmentMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HelpMenu {
            get {
                return ResourceManager.GetString("HelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High woltage inspection device.
        /// </summary>
        internal static string HighWoltageLabel {
            get {
                return ResourceManager.GetString("HighWoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal surface.
        /// </summary>
        internal static string HorizantalaVirsmaLabel {
            get {
                return ResourceManager.GetString("HorizantalaVirsmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string KopaLabel {
            get {
                return ResourceManager.GetString("KopaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time.
        /// </summary>
        internal static string LaiksKopaLabel {
            get {
                return ResourceManager.GetString("LaiksKopaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string LogoLabel {
            get {
                return ResourceManager.GetString("LogoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low woltage inspection device.
        /// </summary>
        internal static string LowWoltageLabel {
            get {
                return ResourceManager.GetString("LowWoltageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        internal static string MailLabel {
            get {
                return ResourceManager.GetString("MailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterproofing membrane name.
        /// </summary>
        internal static string MembraneNameLabel {
            get {
                return ResourceManager.GetString("MembraneNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterproofing membrane thickness.
        /// </summary>
        internal static string MembraneThicknessLabel {
            get {
                return ResourceManager.GetString("MembraneThicknessLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterproofing membrane type.
        /// </summary>
        internal static string MembraneTypeLabel {
            get {
                return ResourceManager.GetString("MembraneTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string NoLabel {
            get {
                return ResourceManager.GetString("NoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifiable area.
        /// </summary>
        internal static string ParbaudamaPlatibaLabel {
            get {
                return ResourceManager.GetString("ParbaudamaPlatibaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete time.
        /// </summary>
        internal static string ParbaudePabeigtaLabel {
            get {
                return ResourceManager.GetString("ParbaudePabeigtaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string ParbaudeUzsaktaLabel {
            get {
                return ResourceManager.GetString("ParbaudeUzsaktaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check was done by.
        /// </summary>
        internal static string ParbaudiVeicaLabel {
            get {
                return ResourceManager.GetString("ParbaudiVeicaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer representative.
        /// </summary>
        internal static string PasutitajaParstavisLabel {
            get {
                return ResourceManager.GetString("PasutitajaParstavisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string PievienotLbel {
            get {
                return ResourceManager.GetString("PievienotLbel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionLabel {
            get {
                return ResourceManager.GetString("QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        internal static string SerialNumberLabel {
            get {
                return ResourceManager.GetString("SerialNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sertificate number.
        /// </summary>
        internal static string SertificateNumberLabel {
            get {
                return ResourceManager.GetString("SertificateNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        internal static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport costs.
        /// </summary>
        internal static string TransportaIzdevumiLabel {
            get {
                return ResourceManager.GetString("TransportaIzdevumiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company info.
        /// </summary>
        internal static string UznemumaDatiLabel {
            get {
                return ResourceManager.GetString("UznemumaDatiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT %.
        /// </summary>
        internal static string VatLabel {
            get {
                return ResourceManager.GetString("VatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical surface (parapet, wall).
        /// </summary>
        internal static string VerikalaVirsmaLabel {
            get {
                return ResourceManager.GetString("VerikalaVirsmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string YesLabel {
            get {
                return ResourceManager.GetString("YesLabel", resourceCulture);
            }
        }
    }
}
